// Generated by scripts/build-icons.mjs from lucide-static (ISC license, https://lucide.dev) plus the hockey icons drawn there — do not edit by hand.
const ICONS = {
  "select": "<path d=\"M12.586 12.586 19 19\" /><path d=\"M3.688 3.037a.497.497 0 0 0-.651.651l6.5 15.999a.501.501 0 0 0 .947-.062l1.569-6.083a2 2 0 0 1 1.448-1.479l6.124-1.579a.5.5 0 0 0 .063-.947z\" />", // lucide: mouse-pointer
  "pan": "<path d=\"M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2\" /><path d=\"M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2\" /><path d=\"M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8\" /><path d=\"M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15\" />", // lucide: hand
  "skater": "<circle cx=\"15.5\" cy=\"4.5\" r=\"2.5\" /><path d=\"M13.5 8 8 12.5\" /><path d=\"m8 12.5 5 3-1.5 5.5\" /><path d=\"M8 12.5 2.5 19\" /><path d=\"m12 9.5 3 2 5 7\" /><path d=\"m20 18.5 3-2\" />", // drawn for this app
  "coach": "<path d=\"M12 3l9 9-9 9-9-9z\" /><path d=\"M14 10.5a2.6 2.6 0 1 0 0 3\" />", // drawn for this app
  "goalie": "<path d=\"M12 2a8 8 0 0 0-8 8v4a8 8 0 0 0 16 0v-4a8 8 0 0 0-8-8z\" /><path d=\"M6.5 9h11\" /><path d=\"M7 14h10\" /><path d=\"M9.5 9v9.5\" /><path d=\"M14.5 9v9.5\" />", // drawn for this app
  "contact": "<circle cx=\"6.5\" cy=\"12\" r=\"4\" /><circle cx=\"17.5\" cy=\"12\" r=\"4\" /><path d=\"M12 4v3\" /><path d=\"M12 17v3\" /><path d=\"m8.5 5.5 1 2\" /><path d=\"m15.5 5.5-1 2\" />", // drawn for this app
  "arrow": "<path d=\"M4 19c3-6 7-10 15-12\" /><path d=\"M13.4 4.8 19 7l-4 4.5\" />", // drawn for this app
  "cone": "<path d=\"m20.9 18.55-8-15.98a1 1 0 0 0-1.8 0l-8 15.98\" /><ellipse cx=\"12\" cy=\"19\" rx=\"9\" ry=\"3\" />", // lucide: cone
  "minicone": "<path d=\"m8 17 4-10 4 10\" /><ellipse cx=\"12\" cy=\"18\" rx=\"6\" ry=\"2\" />", // drawn for this app
  "tire": "<circle cx=\"12\" cy=\"12\" r=\"9\" /><circle cx=\"12\" cy=\"12\" r=\"3.5\" />", // drawn for this app
  "puck": "<ellipse cx=\"12\" cy=\"9\" rx=\"8\" ry=\"3\" /><path d=\"M4 9v5a8 3 0 0 0 16 0V9\" />", // drawn for this app
  "pile": "<path d=\"M4 10h16\" /><path d=\"m5 10 1.6 11h10.8L19 10\" /><ellipse cx=\"9\" cy=\"6.5\" rx=\"3.5\" ry=\"1.5\" /><ellipse cx=\"15.5\" cy=\"5\" rx=\"3.5\" ry=\"1.5\" /><path d=\"M12 5.8V8\" />", // drawn for this app
  "net": "<path d=\"M7 3v18\" /><path d=\"M7 4h4a8 8 0 0 1 0 16H7\" /><path d=\"M7 12h12\" /><path d=\"M12 4.5v15\" />", // drawn for this app
  "obstacle": "<rect x=\"3\" y=\"7\" width=\"18\" height=\"10\" rx=\"2\" /><path d=\"M8 7v10\" /><path d=\"M16 7v10\" />", // drawn for this app
  "raisedpad": "<rect x=\"3\" y=\"5\" width=\"18\" height=\"5\" rx=\"1.5\" /><circle cx=\"7\" cy=\"16\" r=\"3\" /><circle cx=\"17\" cy=\"16\" r=\"3\" />", // drawn for this app
  "jumppad": "<rect x=\"3\" y=\"16\" width=\"18\" height=\"4\" rx=\"1\" /><path d=\"M5 13c3-8 11-8 14 0\" /><path d=\"M18.3 8.1 19 12l-3.9-.7\" />", // drawn for this app
  "barricade": "<rect x=\"2\" y=\"9\" width=\"20\" height=\"6\" rx=\"1\" /><path d=\"m7 9-4 4\" /><path d=\"m12 9-5 6\" /><path d=\"m17 9-5 6\" /><path d=\"m21.5 10-4.5 5\" />", // drawn for this app
  "zone": "<path d=\"M5 3a2 2 0 0 0-2 2\" /><path d=\"M19 3a2 2 0 0 1 2 2\" /><path d=\"M21 19a2 2 0 0 1-2 2\" /><path d=\"M5 21a2 2 0 0 1-2-2\" /><path d=\"M9 3h1\" /><path d=\"M9 21h1\" /><path d=\"M14 3h1\" /><path d=\"M14 21h1\" /><path d=\"M3 9v1\" /><path d=\"M21 9v1\" /><path d=\"M3 14v1\" /><path d=\"M21 14v1\" />", // lucide: square-dashed
  "text": "<path d=\"M12 4v16\" /><path d=\"M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2\" /><path d=\"M9 20h6\" />", // lucide: type
  "undo": "<path d=\"M9 14 4 9l5-5\" /><path d=\"M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11\" />", // lucide: undo-2
  "redo": "<path d=\"m15 14 5-5-5-5\" /><path d=\"M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13\" />", // lucide: redo-2
  "play": "<path d=\"M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z\" />", // lucide: play
  "pause": "<rect x=\"14\" y=\"3\" width=\"5\" height=\"18\" rx=\"1\" /><rect x=\"5\" y=\"3\" width=\"5\" height=\"18\" rx=\"1\" />", // lucide: pause
  "stop": "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />", // lucide: square
  "notes": "<path d=\"M21 9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2z\" /><path d=\"M15 3v5a1 1 0 0 0 1 1h5\" />", // lucide: sticky-note
  "edit": "<path d=\"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z\" /><path d=\"m15 5 4 4\" />", // lucide: pencil
  "up": "<path d=\"m18 15-6-6-6 6\" />", // lucide: chevron-up
  "down": "<path d=\"m6 9 6 6 6-6\" />", // lucide: chevron-down
  "copy": "<rect width=\"14\" height=\"14\" x=\"8\" y=\"8\" rx=\"2\" ry=\"2\" /><path d=\"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2\" />", // lucide: copy
  "x": "<path d=\"M18 6 6 18\" /><path d=\"m6 6 12 12\" />", // lucide: x
  "check": "<path d=\"M20 6 9 17l-5-5\" />", // lucide: check
  "library": "<path d=\"m16 6 4 14\" /><path d=\"M12 6v14\" /><path d=\"M8 8v12\" /><path d=\"M4 4v16\" />", // lucide: library
  "calendar": "<path d=\"M8 2v3\" /><path d=\"M16 2v3\" /><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" /><path d=\"M3 9h18\" />", // lucide: calendar
  "prev": "<path d=\"m15 18-6-6 6-6\" />", // lucide: chevron-left
  "next": "<path d=\"m9 18 6-6-6-6\" />", // lucide: chevron-right
  "rotate": "<path d=\"M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8\" /><path d=\"M21 3v5h-5\" />", // lucide: rotate-cw
  "fullscreen": "<path d=\"M8 3H5a2 2 0 0 0-2 2v3\" /><path d=\"M21 8V5a2 2 0 0 0-2-2h-3\" /><path d=\"M3 16v3a2 2 0 0 0 2 2h3\" /><path d=\"M16 21h3a2 2 0 0 0 2-2v-3\" />", // lucide: maximize
  "unfullscreen": "<path d=\"M8 3v3a2 2 0 0 1-2 2H3\" /><path d=\"M21 8h-3a2 2 0 0 1-2-2V3\" /><path d=\"M3 16h3a2 2 0 0 1 2 2v3\" /><path d=\"M16 21v-3a2 2 0 0 1 2-2h3\" />", // lucide: minimize
  "list": "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /><path d=\"M21 9H3\" /><path d=\"M21 15H3\" />", // lucide: rows-3
  "focus": "<rect width=\"14\" height=\"20\" x=\"5\" y=\"2\" rx=\"2\" ry=\"2\" /><path d=\"M12 18h.01\" />", // lucide: smartphone
  "sync": "<path d=\"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8\" /><path d=\"M21 3v5h-5\" /><path d=\"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16\" /><path d=\"M8 16H3v5\" />", // lucide: refresh-cw
  "eye": "<path d=\"M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0\" /><circle cx=\"12\" cy=\"12\" r=\"3\" />", // lucide: eye
  "eyeoff": "<path d=\"M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49\" /><path d=\"M14.084 14.158a3 3 0 0 1-4.242-4.242\" /><path d=\"M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143\" /><path d=\"m2 2 20 20\" />", // lucide: eye-off
  "focusarea": "<path d=\"M3 7V5a2 2 0 0 1 2-2h2\" /><path d=\"M17 3h2a2 2 0 0 1 2 2v2\" /><path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" /><path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" />", // lucide: scan
  "account": "<circle cx=\"12\" cy=\"12\" r=\"10\" /><circle cx=\"12\" cy=\"10\" r=\"3\" /><path d=\"M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662\" />", // lucide: circle-user
  "signout": "<path d=\"m16 17 5-5-5-5\" /><path d=\"M21 12H9\" /><path d=\"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4\" />", // lucide: log-out
  "mic": "<path d=\"M12 19v3\" /><path d=\"M19 10v2a7 7 0 0 1-14 0v-2\" /><rect x=\"9\" y=\"2\" width=\"6\" height=\"13\" rx=\"3\" />", // lucide: mic
  "video": "<path d=\"m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5\" /><rect x=\"2\" y=\"6\" width=\"14\" height=\"12\" rx=\"2\" />", // lucide: video
  "qp": "<path d=\"M12 17v5\" /><path d=\"M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z\" />", // lucide: pin
};

/** Inline SVG markup for a named icon (24×24 viewBox, stroked with currentColor). */
export function icon(name, cls = '') {
  const body = ICONS[name];
  if (!body) return '';
  return `<svg class="lucide lucide-${name}${cls ? ' ' + cls : ''}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
}

/** Fill every element carrying data-icon with its SVG. */
export function hydrateIcons(root = document) {
  root.querySelectorAll('[data-icon]').forEach(el => { el.innerHTML = icon(el.dataset.icon); });
}
