// Regenerates js/icons.js from lucide-static (run: npm run icons)
import { readFileSync, writeFileSync } from 'node:fs';

// app name -> lucide icon candidates (first that exists wins)
const WANTED = {
  select: ['mouse-pointer'], pan: ['hand'], skater: ['user-round', 'user'],
  coach: ['clipboard-list'], goalie: ['shield'], contact: ['zap'], arrow: ['move-up-right', 'arrow-up-right'],
  cone: ['cone', 'triangle'], minicone: ['triangle'], tire: ['life-buoy'], puck: ['circle-dot'],
  pile: ['database'], net: ['grid-3x3', 'grid'], obstacle: ['rectangle-horizontal', 'minus'],
  raisedpad: ['layers', 'layers-3'], jumppad: ['mountain'], barricade: ['construction', 'traffic-cone'],
  zone: ['square-dashed', 'box-select'], text: ['type'], erase: ['eraser'],
  undo: ['undo-2'], redo: ['redo-2'], play: ['play'], pause: ['pause'], stop: ['square'],
  notes: ['sticky-note'], edit: ['pencil'], up: ['chevron-up'], down: ['chevron-down'],
  copy: ['copy'], x: ['x'], check: ['check'], library: ['library', 'library-big'],
};

const out = {};
const missing = [];
for (const [name, candidates] of Object.entries(WANTED)) {
  let body = null, used = null;
  for (const c of candidates) {
    try {
      const svg = readFileSync(new URL(`../node_modules/lucide-static/icons/${c}.svg`, import.meta.url), 'utf8');
      body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '').replace(/<!--[\s\S]*?-->/g, '').trim().replace(/\n\s*/g, '');
      used = c;
      break;
    } catch { /* try next */ }
  }
  if (!body) { missing.push(`${name} (${candidates.join(', ')})`); continue; }
  out[name] = { used, body };
}
if (missing.length) { console.error('MISSING:', missing.join(' | ')); process.exit(1); }

const lines = Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v.body)}, // lucide: ${v.used}`);
const js = [
  '// Generated by scripts/build-icons.mjs from lucide-static (ISC license, https://lucide.dev) — do not edit by hand.',
  'const ICONS = {',
  ...lines,
  '};',
  '',
  '/** Inline SVG markup for a named icon (24×24 viewBox, stroked with currentColor). */',
  'export function icon(name, cls = \'\') {',
  '  const body = ICONS[name];',
  '  if (!body) return \'\';',
  '  return `<svg class="lucide lucide-${name}${cls ? \' \' + cls : \'\'}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;',
  '}',
  '',
  '/** Fill every element carrying data-icon with its SVG. */',
  'export function hydrateIcons(root = document) {',
  '  root.querySelectorAll(\'[data-icon]\').forEach(el => { el.innerHTML = icon(el.dataset.icon); });',
  '}',
  '',
].join('\n');
writeFileSync(new URL('../js/icons.js', import.meta.url), js);
console.log(`js/icons.js: ${Object.keys(out).length} icons`);
